### ISSUE TITLE
 if not index.is_trained and INDEX_KEY != "IDMap,Flat ;  trainning one time？

### ISSUE THREAD

**Issue by fengyix** [waltyou/faiss-web-service#4]
when INDEX_KEY = "IDMap,IMI2x10,Flat" ,

in "train_index.py" line 49,just training one time?  index.is_trained :（False -> True）；  line 59 no training 

Is there have a problem? 

###############################################

 if not index.is_trained and INDEX_KEY != "IDMap,Flat":
                index.train(features)

###########################################

**Comment by waltyou** [comment]
Thanks for asking that.  You are right. it will only train once if the statement `not index.is_trained and INDEX_KEY != "IDMap,Flat"` is true. 

I write that is because i want to speed up the training and adding feature process. And 500 images will have 500 * 100 ([NUM_FEATURES](https://github.com/waltyou/faiss-web-service/blob/master/src/config.py#L32)) = 50000 features. It is quite enough for my training.

Feel free to increase the batch size which is based on your own situation (memory, total image count, each features of one image ).

**Comment by fengyix** [comment]
thanks
